Slots inheritance and properly readonly, disable and dense props passing to CountrySelect control
CdTgr/vue3-q-tel-input pull request #20
Opened 2023-01-15 12:33 UTC by FragsterAt

fixes #18 #19

2023-01-16 20:08 UTC, CdTgr requested changes
Pretty good ❤️

2023-01-16 20:08 UTC, CdTgr commented on .gitignore
> +yarn.lock
```suggestion
```
Lock file is required

2023-01-16 20:08 UTC, CdTgr commented on src/component/Index.vue
> +    disable: { type: Boolean, default: () => false}
```suggestion
    dense: { type: Boolean, default: () => false },
    disable: { type: Boolean, default: () => false },
```

2023-01-16 20:08 UTC, CdTgr commented on src/component/Index.vue
> +  setup(props, { slots }) {
```suggestion
  setup(_, { slots }) {
```

2023-01-18 08:55 UTC, FragsterAt reviewed
Nice!

2023-01-19 17:33 UTC, CdTgr requested changes

2023-01-19 17:33 UTC, CdTgr commented on src/component/Index.vue
> +  setup(props, { slots }) {
@FragsterAt Missed this?

2023-01-25 21:54 UTC, merged

2023-05-04 16:40 UTC, Iscrimou commented
now readonly, disable and dense props are affecting only the country selector, not the input

![Screenshot 2023-05-04 at 13-38-11 SocialHub Contatos](https://user-images.githubusercontent.com/62183829/236269580-6048bf26-8315-4997-b750-8561322c6f07.png)
![Captura de tela de 2023-05-04 13-38-23](https://user-images.githubusercontent.com/62183829/236269619-11880c36-5b63-4f72-83e4-2a2c131e8961.png)